name: Build Projects

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Set Path
        run: cd $GITHUB_WORKSPACE
      - name: clang-format lint
        uses: yshui/git-clang-format-lint@v1.3
      - name: Build IBEngine Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:IBEngine -p:Configuration=Debug -p:Platform="x64" -m
      - name: Build IBEngine Release|x64
        run: msbuild VisualStudio\IceBox.sln -t:IBEngine -p:Configuration=Release -p:Platform="x64" -m
      - name: Build Sample01 Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:Sample01 -p:Configuration=Debug -p:Platform="x64" -m
      - name: Build Sample01 Release|x64
        run: msbuild VisualStudio\IceBox.sln -t:Sample01 -p:Configuration=Release -p:Platform="x64" -m
